// Gianluca Mazzini @2022- Version 4.6
#include <stdio.h>

static const char qsoz_page[]=
  "<!-- Gianluca Mazzini @2022- Version 4.1 -->\n"
  "<head>\n"
  "  <meta charset=\"UTF-8\">\n"
  "  <meta http-equiv=\"Cache-Control\" content=\"no-store\">\n"
  "  <title>LOG by IK4LZH</title>\n"
  "  <style>\n"
  "html, body {\n"
  "  height: 100%;\n"
  "  margin: 0;\n"
  "  display: flex;\n"
  "  flex-direction: column;\n"
  "  background-color: #F9F4B7;\n"
  "}\n"
  "\n"
  "td {\n"
  "  border: 1px solid red;\n"
  "  border-collapse: collapse;\n"
  "  border-style: dotted;\n"
  "}\n"
  "\n"
  ".guess {\n"
  "  background: none;\n"
  "  border: none;\n"
  "  padding: 0;\n"
  "  margin: 0;\n"
  "  font: inherit;\n"
  "  color: inherit;\n"
  "  cursor: pointer; \n"
  "}\n"
  "\n"
  ".guess:hover {\n"
  "  font-weight: bold;  \n"
  "}\n"
  "\n"
  ".btn {\n"
  "  font-family: 'Courier New',monospace;\n"
  "  background-color: #666699;\n"
  "  border: none;\n"
  "  color: #F9F4B7;\n"
  "  padding: 5px 12px;\n"
  "  text-align: center;\n"
  "  text-decoration: none;\n"
  "  display: inline-block;\n"
  "  font-size: 16px;\n"
  "  border-radius: 15px;\n"
  "  outline:none;\n"
  "  margin-left: 3px;\n"
  "  margin-bottom: 2px;\n"
  "  margin-top: 2px;\n"
  "}\n"
  "\n"
  ".btn:hover {\n"
  "  background-color: #992C15;\n"
  "}\n"
  "\n"
  ".myq1 {\n"
  "  text-align: center;\n"
  "}\n"
  "\n"
  ".myh1 {\n"
  "  color: red;\n"
  "  font-weight: bold;\n"
  "  margin-bottom: 5px;\n"
  "  line-height: 0;\n"
  "}\n"
  "\n"
  ".myh2 {\n"
  "  color: blue;\n"
  "  font-weight: bold;\n"
  "  margin-bottom: 5px;\n"
  "  line-height: 0;\n"
  "}\n"
  "\n"
  ".split{\n"
  "  display: flex;\n"
  "  width: 100%;\n"
  "  height: 100vh;\n"
  "  gap: 10px;\n"
  "  box-sizing: border-box;\n"
  "  padding: 10px;\n"
  "}\n"
  "\n"
  ".out{\n"
  "  flex: 1;\n"
  "  min-width: 0;\n"
  "  overflow-y: auto;\n"
  "  overflow-x: auto;\n"
  "  border: 1px solid #ccc;\n"
  "  padding: 10px;\n"
  "  box-sizing: border-box;\n"
  "  background-color: #F9F4B7;\n"
  "}\n"
  "\n"
  ".myb2 {\n"
  "  font-family: 'Courier New',monospace;\n"
  "  background-color: #666699;\n"
  "  border: none;\n"
  "  color: #F9F4B7;\n"
  "  padding: 1px 5px;\n"
  "  text-align: center;\n"
  "  text-decoration: none;\n"
  "  display: inline-block;\n"
  "  font-size: 12px;\n"
  "  border-radius: 10px;\n"
  "  outline:none;\n"
  "  margin-left: 2px;\n"
  "  margin-bottom: 1px;\n"
  "  margin-top: 1px;\n"
  "}\n"
  "\n"
  ".myb2:hover {\n"
  "  background-color: #992C15;\n"
  "}\n"
  "\n"
  ".myf1 {\n"
  "  font-family: 'Courier New',monospace;\n"
  "}\n"
  "\n"
  ".myf2 {\n"
  "  font-family: 'Courier New',monospace;\n"
  "  background-color: #ffcccc;\n"
  "}\n"
  "\n"
  ".gchart {\n"
  "  min-width: 500px;\n"
  "}\n"
  "\n"
  ".gchart svg {\n"
  "  display: block;\n"
  "  overflow: visible;\n"
  "}\n"
  "\n"
  ".chart-axis {\n"
  "  stroke: currentColor;\n"
  "  stroke-width: 1;\n"
  "}\n"
  "\n"
  ".chart-grid {\n"
  "  stroke: currentColor;\n"
  "  stroke-width: 0.5;\n"
  "  stroke-opacity: 0.25;\n"
  "}\n"
  "\n"
  ".chart-label {\n"
  "  fill: currentColor;\n"
  "  font-family: 'Courier New',monospace;\n"
  "  font-size: 11px;\n"
  "}\n"
  "\n"
  ".chart-series {\n"
  "  fill: none;\n"
  "  stroke: currentColor;\n"
  "  stroke-width: 1.5;\n"
  "}\n"
  "\n"
  ".chart-points {\n"
  "  stroke-dasharray: 8 3;\n"
  "}\n"
  "\n"
  ".chart-mults {\n"
  "  stroke-dasharray: 3 3;\n"
  "}\n"
  "\n"
  ".chart-score {\n"
  "  stroke-width: 2.5;\n"
  "  stroke-dasharray: 12 3 2 3;\n"
  "}\n"
  "  </style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"hh1\">\n"
  "  <input class=\"myf2\" id=\"l01\" placeholder=\"login\" maxlength=\"6\" minlength=\"4\" required>\n"
  "  <input class=\"myf2\" id=\"l02\" type=\"password\" placeholder=\"password\" maxlength=\"16\" minlength=\"6\" required>\n"
  "  <button class=\"btn\" id=\"l03\">LOGIN</button>\n"
  "</div>\n"
  "<div id=\"hh2\">\n"
  "  <table>\n"
  "    <td class=\"myq1\"><table>\n"
  "      <tr><td><label class=\"myf1\">Call</label></td><td><input class=\"myf2\" id=\"call\" maxlength=\"20\" size=\"10\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">Freq</label></td><td><input class=\"myf2\" id=\"freq\" maxlength=\"10\" size=\"10\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">Mode</label></td><td><input class=\"myf2\" type=\"text\" id=\"mode\" maxlength=\"8\" size=\"6\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">SigTX</label></td><td><input class=\"myf2\" type=\"text\" id=\"sigtx\" maxlength=\"10\" size=\"6\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">SigRX</label></td><td><input class=\"myf2\" type=\"text\" id=\"sigrx\" maxlength=\"10\" size=\"6\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">Contest</label></td><td><input class=\"myf2\" disabled type=\"text\" id=\"contest\" maxlength=\"12\" size=\"12\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">ConTx</label></td><td><input class=\"myf2\" disabled type=\"text\" id=\"contx\" maxlength=\"12\" size=\"12\" autocomplete=\"off\"></td></tr>\n"
  "      <tr><td><label class=\"myf1\">ConRx</label></td><td><input class=\"myf2\" disabled type=\"text\" id=\"conrx\" maxlength=\"12\" size=\"12\" autocomplete=\"off\"></td></tr>\n"
  "      </table> \n"
  "      <button class=\"btn\" id=\"a23\">Start</button><button class=\"btn\" id=\"a26\">End</button><br>\n"
  "      <button class=\"btn\" id=\"a24\">QRZ.com</button><button class=\"btn\" id=\"a25\">QRZ.ru</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <button class=\"btn\" id=\"t51\">51</button><br>\n"
  "      <button class=\"btn\" id=\"t53\">53</button><br>\n"
  "      <button class=\"btn\" id=\"t55\">55</button><br>\n"
  "      <button class=\"btn\" id=\"t56\">56</button><br>\n"
  "      <button class=\"btn\" id=\"t57\">57</button><br>\n"
  "      <button class=\"btn\" id=\"t58\">58</button><br>\n"
  "      <button class=\"btn\" id=\"t59\">59</button><br>\n"
  "      <button class=\"btn\" id=\"t59+10\">59+10</button><br>\n"
  "      <button class=\"btn\" id=\"t59+20\">59+20</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <button class=\"btn\" id=\"r51\">51</button><br>\n"
  "      <button class=\"btn\" id=\"r53\">53</button><br>\n"
  "      <button class=\"btn\" id=\"r55\">55</button><br>\n"
  "      <button class=\"btn\" id=\"r56\">56</button><br>\n"
  "      <button class=\"btn\" id=\"r57\">57</button><br>\n"
  "      <button class=\"btn\" id=\"r58\">58</button><br>\n"
  "      <button class=\"btn\" id=\"r59\">59</button><br>\n"
  "      <button class=\"btn\" id=\"r59+10\">59+10</button><br>\n"
  "      <button class=\"btn\" id=\"r59+20\">59+20</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <button class=\"btn\" id=\"a01\">List</button><button class=\"btn\" id=\"a02\">&#8679;</button><button class=\"btn\" id=\"a03\">&#8681;</button><button class=\"btn\" id=\"a04\">R</button><button class=\"btn\" id=\"a05\">G</button><br>\n"
  "      <button class=\"btn\" id=\"a06\">LFind</button><button class=\"btn\" id=\"a07\">&#8679;</button><button class=\"btn\" id=\"a08\">&#8681;</button><br>\n"
  "      <button class=\"btn\" id=\"a28\">LCon</button><button class=\"btn\" id=\"a29\">&#8679;</button><button class=\"btn\" id=\"a30\">&#8681;</button><br>\n"
  "      <button class=\"btn\" id=\"b08\">ConOO</button><span id=\"c08\"></span><button class=\"btn\" id=\"b22\">ConTX++</button><span id=\"c22\"></span><br>\n"
  "      <button class=\"btn\" id=\"a27\">ConList</button><button class=\"btn\" id=\"a31\">ConDetails</button><br>\n"
  "      <button class=\"btn\" id=\"a14\">ConGraph</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <button class=\"btn\" id=\"b01\">RigOO</button><span id=\"c01\"></span><br>\n"
  "      <button class=\"btn\" id=\"b02\">RTX&#8680;1</button><button class=\"btn\" id=\"b03\">1&#8680;RTX</button><br>\n"
  "      <span id=\"c23\"></span><br>\n"
  "      <button class=\"btn\" id=\"b04\">RTX&#8680;2</button><button class=\"btn\" id=\"b05\">2&#8680;RTX</button><br>\n"
  "      <span id=\"c45\"></span><br>\n"
  "      <button class=\"btn\" id=\"b06\">RTX&#8680;3</button><button class=\"btn\" id=\"b07\">3&#8680;RTX</button><br>\n"
  "      <span id=\"c67\"></span><br>\n"
  "      <button class=\"btn\" onclick=\"cmd5(1)\">Udef1</button><button class=\"btn\" onclick=\"cmd5(2)\">Udef2</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <input type=\"file\" id=\"ff\" hidden>\n"
  "      <label class=\"btn\" for=\"ff\">File</label><br>\n"
  "      <button class=\"btn\" id=\"a15\">adi&#8680;</button><button class=\"btn\" id=\"a16\">lzh&#8680;</button><button class=\"btn\" id=\"a22\">cbr&#8680;</button><br>\n"
  "      <button class=\"btn\" id=\"a20\">&#8680;adi</button><button class=\"btn\" id=\"a21\">&#8680;cbr</button><br>\n"
  "      <button class=\"btn\" id=\"a17\">QSL.lotw</button><br>\n"
  "      <button class=\"btn\" id=\"a18\">QSL.eqsl</button><br>\n"
  "      <button class=\"btn\" id=\"a19\">QSL.qrz</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <button class=\"btn\" id=\"b09\">PH</button><span id=\"c09\"></span>\n"
  "      <button class=\"btn\" id=\"b10\">CW</button><span id=\"c10\"></span>\n"
  "      <button class=\"btn\" id=\"b11\">DG</button><span id=\"c11\"></span><br>\n"
  "      <button class=\"btn\" id=\"b12\">10</button><span id=\"c12\"></span>\n"
  "      <button class=\"btn\" id=\"b13\">15</button><span id=\"c13\"></span>\n"
  "      <button class=\"btn\" id=\"b14\">20</button><span id=\"c14\"></span><br>\n"
  "      <button class=\"btn\" id=\"b15\">40</button><span id=\"c15\"></span>\n"
  "      <button class=\"btn\" id=\"b16\">80</button><span id=\"c16\"></span>\n"
  "      <button class=\"btn\" id=\"b17\">160</button><span id=\"c17\"></span><br>\n"
  "      <button class=\"btn\" id=\"b18\">12</button><span id=\"c18\"></span>\n"
  "      <button class=\"btn\" id=\"b19\">17</button><span id=\"c19\"></span>\n"
  "      <button class=\"btn\" id=\"b20\">30</button><span id=\"c20\"></span><br>\n"
  "      <button class=\"btn\" id=\"b21\">60</button><span id=\"c21\"></span><br>\n"
  "      <button class=\"btn\" id=\"a13\">Cluster</button>\n"
  "    </td>\n"
  "    <td class=\"myq1\">\n"
  "      <h1><span id=\"o_call\"></span></h1>\n"
  "      <span id=\"o_time\"></span><br>\n"
  "      <span id=\"o_ota\"></span><br>\n"
  "      <button class=\"btn\" id=\"a09\">Apply</button><button class=\"btn\" id=\"a10\">Report</button><br>\n"
  "      <button class=\"btn\" id=\"a11\">Curio</button><button class=\"btn\" id=\"a12\">Activity</button><br>\n"
  "      <button class=\"btn\" id=\"a32\">CTY</button><button class=\"btn\" id=\"a33\" hidden>Completion</button><button class=\"btn\" id=\"a34\" hidden>Users</button><br>\n"
  "      <label class=\"myf1\">MyPage </label><input class=\"myf2\" id=\"mypage\" maxlength=\"3\" size=\"3\" autocomplete=\"off\"><br>\n"
  "      <label class=\"myf1\">Base </label><span id=\"base\"></span><br>\n"
  "      <label class=\"myf1\">Release </label><span id=\"release\"></span><br>\n"
  "    </td>\n"
  "  </table>\n"
  "</div>\n"
  "<div class=\"split\">\n"
  "  <div class=\"out\" id=\"out\"></div>\n"
  "  <div class=\"out\" id=\"out2\"></div>\n"
  "</div>\n"
  "<script type=\"module\">\n"
  "const l01 = document.getElementById(\"l01\");\n"
  "const l02 = document.getElementById(\"l02\");\n"
  "const imypage = document.getElementById(\"mypage\");\n"
  "let v = new Array(22+1).fill(0);\n"
  "  \n"
  "const inputs = [\"call\", \"freq\", \"mode\", \"sigtx\", \"sigrx\", \"contest\", \"contx\", \"conrx\"];\n"
  "inputs.forEach(id => {\n"
  "  const el = document.getElementById(id);\n"
  "  if (!el) return;\n"
  "  el.addEventListener(\"keydown\", e => {\n"
  "    if (e.key === \",\") e.preventDefault();\n"
  "    if (id === \"call\" && e.key === \"Enter\") {\n"
  "      e.preventDefault();\n"
  "      document.getElementById(\"a23\").click();\n"
  "    }\n"
  "  });\n"
  "  el.addEventListener(\"input\", async () => {\n"
  "    const pos = el.selectionStart;\n"
  "    const newValue = el.value.replace(/,/g, \"\").toUpperCase();\n"
  "    const diff = el.value.length - newValue.length;\n"
  "    el.value = newValue;\n"
  "    el.setSelectionRange(pos - diff, pos - diff);\n"
  "    if (id === \"call\") {\n"
  "      const r = await fetch(\"qsoz?op=guess\", {\n"
  "        method: \"POST\",\n"
  "        cache: \"no-store\",\n"
  "        credentials: \"same-origin\",\n"
  "        headers: { \"Content-Type\": \"text/plain\" },\n"
  "        body: el.value\n"
  "       });\n"
  "       document.getElementById(\"out\").innerHTML = await r.text();\n"
  "    }\n"
  "  });\n"
  "});\n"
  "  \n"
  "let base = 0;\n"
  "let mypage = 0;\n"
  "let mysync = 0;\n"
  "let delta = 0;\n"
  "let ota = \"\";\n"
  "let filter = \"\";\n"
  "let start = \"\";\n"
  "let b02f, b02m, b04f, b04m, b06f, b06m;\n"
  "\n"
  "function setchecks() {\n"
  "  for (let i = 1; i <= 22; i++) {\n"
  "    const id = \"c\" + String(i).padStart(2, \"0\");\n"
  "    const el = document.getElementById(id);\n"
  "    if (el) {\n"
  "      el.textContent = v[i] === 1 ? \"☑️\" : \"☐\";\n"
  "    }\n"
  "  }\n"
  "}\n"
  " \n"
  "async function usersAction(action,id) {\n"
  "  const root = document.getElementById(id);\n"
  "  if (!root) return;\n"
  "  const body = new URLSearchParams({ota,action});\n"
  "  root.querySelectorAll('[name]').forEach(el => body.set(el.name, el.value));\n"
  "  const out = document.getElementById(\"out2\");\n"
  "  out.textContent = \"Waiting\";\n"
  "  const r = await fetch(\"qsoz?op=users\", {method:\"POST\",cache:\"no-store\",credentials:\"same-origin\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body});\n"
  "  out.innerHTML = await r.text();\n"
  "}\n"
  "\n"
  "document.querySelectorAll(\"button[id]\").forEach(btn => {\n"
  "  if (btn.id === \"a32\" || btn.id === \"a33\" || btn.id === \"a34\") {\n"
  "    btn.addEventListener(\"click\", async () => {\n"
  "      const out = document.getElementById(\"out2\");\n"
  "      let endpoint = \"qsoz?op=cty\";\n"
  "      let headers = {\"Content-Type\": \"text/plain\"};\n"
  "      let body = ota;\n"
  "      if (btn.id === \"a33\") endpoint = \"qsoz?op=completion\";\n"
  "      else if (btn.id === \"a34\") { endpoint = \"qsoz?op=users\"; headers = {\"Content-Type\": \"application/x-www-form-urlencoded\"}; body = new URLSearchParams({ota,action:\"list\"}); }\n"
  "      out.textContent = \"Waiting\";\n"
  "      const r = await fetch(endpoint, {method:\"POST\",cache:\"no-store\",credentials:\"same-origin\",headers,body});\n"
  "      out.innerHTML = await r.text();\n"
  "    });\n"
  "  }\n"
  "  else if (/^a\\d{2}$/.test(btn.id)) {\n"
  "    btn.addEventListener(\"click\", async () => {\n"
  "      const num = parseInt(btn.id.slice(1), 10);\n"
  "      if (num == 1 || num == 6 || num == 28) base = 0;\n"
  "      else if (num == 2 || num == 7 || num == 29) base -= mypage;\n"
  "      else if (num == 3 || num == 8 || num == 30) base += mypage;\n"
  "      let data = \"\";\n"
  "      if (num >= 15 && num <= 22) {\n"
  "        const file = document.getElementById(\"ff\").files[0];\n"
  "        if (file) {\n"
  "          const plainStream = file.stream();\n"
  "          const plainBlob = await new Response(plainStream).blob();\n"
  "          const buf = await plainBlob.arrayBuffer();\n"
  "          let chunk = 0x8000, bytes = new Uint8Array(buf);\n"
  "          let binary = \"\";\n"
  "          for (let i = 0; i < bytes.length; i += chunk) {\n"
  "            binary += String.fromCharCode(...bytes.subarray(i, i + chunk));\n"
  "          }\n"
  "          data = btoa(binary);\n"
  "        }\n"
  "      }\n"
  "      if (num >= 9 && num <= 22) document.getElementById(\"out2\").textContent = \"Waiting\";\n"
  "      else document.getElementById(\"out\").textContent = \"Waiting\";\n"
  "      if (base < 0) base = 0;\n"
  "      document.getElementById(\"base\").textContent = base;\n"
  "      const body = [\n"
  "        ota,\n"
  "        btn.id,\n"
  "        base,\n"
  "        mypage,\n"
  "        ...inputs.map(id => document.getElementById(id)?.value.trim() || \"-\"),\n"
  "        num === 13 ? v.slice(9, 22).join('') : num === 26 ? start : '',\n"
  "        data\n"
  "      ].join(\",\");\n"
  "      const r = await fetch(\"qsoz?op=proc\", {\n"
  "        method: \"POST\", cache: \"no-store\", credentials: \"same-origin\",\n"
  "        headers: {\"Content-Type\": \"text/csv\"},\n"
  "        body\n"
  "      });\n"
  "      let out = null;\n"
  "      if (num == 5) {\n"
  "        base = parseInt(await r.text(), 10) || 0;\n"
  "        document.getElementById(\"a04\").click();\n"
  "      }\n"
  "      else {\n"
  "        const html = await r.text();\n"
  "        const outnum = +/<!--\\s*(\\d+)\\s*-->/.exec(html)[1];\n"
  "        if (outnum >= 9 && outnum <= 22) out = document.getElementById(\"out2\");\n"
  "        else out = document.getElementById(\"out\");\n"
  "        out.innerHTML = html;\n"
  "      }\n"
  "      if (num == 23) {\n"
  "        const match = out.innerText.match(/Start:\\s*(.+)/);\n"
  "        if (match) start = match[1].trim();\n"
  "        else start = \"\";\n"
  "      }\n"
  "      else if (num == 26) {\n"
  "        start = \"\";\n"
  "        if (v[22] === 1) document.getElementById(\"contx\").value = parseInt(document.getElementById(\"contx\").value) + 1;\n"
  "      }\n"
  "      else if (num == 14) {\n"
  "        renderCharts(out);\n"
  "      }\n"
  "    });\n"
  "  }\n"
  "  else if (btn.id === \"l03\") {\n"
  "    btn.addEventListener(\"click\", async () => {\n"
  "      const r = await fetch(\"qsoz?op=login\", {\n"
  "        method: \"POST\", cache: \"no-store\", credentials: \"same-origin\",\n"
  "        headers: {\"Content-Type\": \"application/x-www-form-urlencoded\"},\n"
  "        body: new URLSearchParams({call:l01.value.trim().toUpperCase(),password:l02.value})\n"
  "      });\n"
  "      [ota, mypage, filter] = (await r.text()).trim().split(\",\");\n"
  "      mypage = Number(mypage);\n"
  "      if (ota.length === 16) {\n"
  "        hh2.style.display = \"block\";\n"
  "        hh1.style.display = \"none\";\n"
  "        document.getElementById(\"o_call\").textContent = l01.value.trim().toUpperCase();\n"
  "        document.getElementById(\"o_ota\").textContent = ota;\n"
  "        document.getElementById(\"mypage\").value = mypage;\n"
  "        document.getElementById(\"a33\").hidden = l01.value.trim().toUpperCase() !== \"IK4LZH\";\n"
  "        document.getElementById(\"a34\").hidden = l01.value.trim().toUpperCase() !== \"IK4LZH\";\n"
  "        for (let i = 0; i < 13; i++) v[9 + i] = +filter[i];\n"
  "        setchecks();\n"
  "      }\n"
  "    });\n"
  "  }\n"
  "  else if (/^b\\d{2}$/.test(btn.id)) {\n"
  "    btn.addEventListener(\"click\", async () => {\n"
  "      const num = parseInt(btn.id.slice(1), 10);\n"
  "      switch (num) {\n"
  "        case 1:\n"
  "          v[1] = 1 - v[1];\n"
  "          if (v[1] === 1) {\n"
  "            document.getElementById(\"freq\").disabled = true;\n"
  "            document.getElementById(\"mode\").disabled = true;\n"
  "          } \n"
  "          else {\n"
  "            document.getElementById(\"freq\").disabled = false;\n"
  "            document.getElementById(\"mode\").disabled = false;\n"
  "          }\n"
  "          break;\n"
  "        case 2:\n"
  "          b02f = document.getElementById(\"freq\").value;\n"
  "          b02m = document.getElementById(\"mode\").value;\n"
  "          document.getElementById(\"c23\").textContent = b02f + \":\" + b02m;\n"
  "          break;\n"
  "        case 3:\n"
  "          if (v[1] === 1 && typeof b02f !== \"undefined\" && typeof b02m !== \"undefined\") {\n"
  "            document.getElementById(\"freq\").value = b02f;\n"
  "            document.getElementById(\"mode\").value = b02m;\n"
  "            radioset(b02f,b02m);\n"
  "          }\n"
  "          break;\n"
  "        case 4:\n"
  "          b04f = document.getElementById(\"freq\").value;\n"
  "          b04m = document.getElementById(\"mode\").value;\n"
  "          document.getElementById(\"c45\").textContent = b04f + \":\" + b04m;\n"
  "          break;\n"
  "        case 5:\n"
  "          if (v[1] === 1 && typeof b04f !== \"undefined\" && typeof b04m !== \"undefined\") {\n"
  "            document.getElementById(\"freq\").value = b04f;\n"
  "            document.getElementById(\"mode\").value = b04m;\n"
  "            radioset(b04f,b04m);\n"
  "          }\n"
  "          break;\n"
  "        case 6:\n"
  "          b06f = document.getElementById(\"freq\").value;\n"
  "          b06m = document.getElementById(\"mode\").value;\n"
  "          document.getElementById(\"c67\").textContent = b06f + \":\" + b06m;\n"
  "          break;\n"
  "        case 7:\n"
  "          if (v[1] === 1 && typeof b06f !== \"undefined\" && typeof b06m !== \"undefined\") {\n"
  "            document.getElementById(\"freq\").value = b06f;\n"
  "            document.getElementById(\"mode\").value = b06m;\n"
  "            radioset(b06f,b06m);\n"
  "          }\n"
  "          break;\n"
  "        case 8:\n"
  "          v[8] = 1 - v[8];\n"
  "          if (v[8] === 1) {\n"
  "            document.getElementById(\"contest\").disabled = false;\n"
  "            document.getElementById(\"contx\").disabled = false;\n"
  "            document.getElementById(\"conrx\").disabled = false;\n"
  "          }\n"
  "          else {\n"
  "            document.getElementById(\"contest\").disabled = true;\n"
  "            document.getElementById(\"contx\").disabled = true;\n"
  "            document.getElementById(\"conrx\").disabled = true;\n"
  "          }\n"
  "          break;\n"
  "        default:\n"
  "          v[num] = 1 - v[num];\n"
  "          break;\n"
  "      }\n"
  "      setchecks();\n"
  "    });\n"
  "  }\n"
  "  else  if (/^t.*/.test(btn.id)) {\n"
  "    btn.addEventListener(\"click\", async (t) => {\n"
  "      document.getElementById(\"sigtx\").value = t.currentTarget.id.slice(1);\n"
  "    });\n"
  "  }\n"
  "  else  if (/^r.*/.test(btn.id)) {\n"
  "    btn.addEventListener(\"click\", async (r) => {\n"
  "      document.getElementById(\"sigrx\").value = r.currentTarget.id.slice(1);\n"
  "    });\n"
  "  }\n"
  "});\n"
  "\n"
  "window.cmd1 = async (a,b) => {\n"
  "  const p = prompt(\"DEL DELETE FT=xxx FREQTX=xxx FR=xxx FREQRX=xxx M=xxx MODE=xxx ST=xxx SIGNALTX=xxx SR=xxx SIGNALRX=xxx C=xxx CALL=xxx DTS=xxx DATETIMESTART=xxx DTE=xxx DATETIMEEND=xxx CO=xxx CONTEST=xxx COT=xxx CONTESTTX=xxx COR=xxx CONTESTRX=xxx\",\"\");\n"
  "  if (p) {\n"
  "    const r = await fetch(\"qsoz?op=cmd\", {\n"
  "      method: \"POST\",\n"
  "      cache: \"no-store\",\n"
  "      credentials: \"same-origin\",\n"
  "      headers: { \"Content-Type\": \"text/csv\" },\n"
  "      body: [ota, a, b, p.toUpperCase()].join(\",\")\n"
  "    });\n"
  "  }\n"
  "};\n"
  "\n"
  "window.cmd2 = async (a) => {\n"
  "  document.getElementById(\"contest\").value = a;\n"
  "};\n"
  "\n"
  "window.cmd3 = async (a,b) => {\n"
  "  document.getElementById(\"call\").value = a;\n"
  "  document.getElementById(\"freq\").value = b;\n"
  "  radioset(b,document.getElementById(\"mode\").value);\n"
  "};\n"
  "\n"
  "window.cmd4 = async (a) => {\n"
  "  document.getElementById(\"call\").value = a;\n"
  "};\n"
  "\n"
  "window.cmd5 = async (a) => {\n"
  "  if (v[1] === 0) return;\n"
  "  const r = await fetch(\"qsoz?op=radio\", {\n"
  "    method: \"POST\",\n"
  "    cache: \"no-store\",\n"
  "    credentials: \"same-origin\",\n"
  "    headers: { \"Content-Type\": \"text/csv\" },\n"
  "    body: [ota, \"U\", `${a}`].join(\",\")\n"
  "  });\n"
  "};\n"
  "\n"
  "setInterval(() => {\n"
  "  for (const id of [\"out\",\"out2\"]) {\n"
  "    const el = document.getElementById(id);\n"
  "    if (el && /^Waiting/i.test(el.textContent)) el.textContent += \".\";\n"
  "  }\n"
  "}, 333);\n"
  "\n"
  "async function radioread() {\n"
  "  if (v[1] === 0) return;\n"
  "  const r = await fetch(\"qsoz?op=radio\", {\n"
  "    method: \"POST\",\n"
  "    cache: \"no-store\",\n"
  "    credentials: \"same-origin\",\n"
  "    headers: { \"Content-Type\": \"text/csv\" },\n"
  "    body: [ota, \"R\", \"0,ND\"].join(\",\")\n"
  "  });\n"
  "  const text = await r.text();\n"
  "  const [freq, mode] = text.split(\",\");\n"
  "  const fff = (freq / 1000).toFixed(1);\n"
  "  document.getElementById(\"freq\").value = fff;\n"
  "  document.getElementById(\"mode\").value = mode;\n"
  "}\n"
  "\n"
  "window.radioset = async (a,b) => {\n"
  "  if (v[1] === 0) return;\n"
  "  const aa = Math.round(a * 1000);\n"
  "  const r = await fetch(\"qsoz?op=radio\", {\n"
  "    method: \"POST\",\n"
  "    cache: \"no-store\",\n"
  "    credentials: \"same-origin\",\n"
  "    headers: { \"Content-Type\": \"text/csv\" },\n"
  "    body: [ota, \"S\", `${aa}:${b}`].join(\",\")\n"
  "  });\n"
  "  const text = await r.text();\n"
  "  const [freq, mode] = text.split(\",\");\n"
  "  const fff = (freq / 1000).toFixed(1);\n"
  "  document.getElementById(\"freq\").value = fff;\n"
  "  document.getElementById(\"mode\").value = mode;\n"
  "}\n"
  " \n"
  "window.timeupdate = async () => {\n"
  "  mysync++;\n"
  "  if (mysync == 60){\n"
  "    mysync = 0;\n"
  "    const r = await fetch(\"qsoz?op=time\");\n"
  "    const t = await r.text();\n"
  "    delta = Number(t) - Math.floor(Date.now() / 1000);\n"
  "  }\n"
  "  const d = new Date(Date.now() + delta * 1000);\n"
  "  const YYYY = d.getUTCFullYear();\n"
  "  const MM = String(d.getUTCMonth() + 1).padStart(2, '0');\n"
  "  const DD = String(d.getUTCDate()).padStart(2, '0');\n"
  "  const hHH = String(d.getUTCHours()).padStart(2, '0');\n"
  "  const mm = String(d.getUTCMinutes()).padStart(2, '0');\n"
  "  const ss = String(d.getUTCSeconds()).padStart(2, '0');\n"
  "  document.getElementById(\"o_time\").textContent = `${YYYY}-${MM}-${DD} ${hHH}:${mm}:${ss} UTC`;\n"
  "}\n"
  "\n"
  "imypage.addEventListener(\"input\", () => {\n"
  "    mypage = Number(imypage.value);\n"
  "});\n"
  "\n"
  "setInterval(radioread, 10000);\n"
  "radioread();\n"
  "setInterval(timeupdate, 1000);\n"
  "timeupdate();\n"
  "setchecks();\n"
  "hh2.style.display = \"none\";\n"
  "hh1.style.display = \"block\";\n"
  "document.getElementById(\"sigtx\").value = \"59\";\n"
  "document.getElementById(\"sigrx\").value = \"59\";\n"
  "document.getElementById(\"base\").textContent = base;\n"
  "async function releaseupdate() {\n"
  "  const el=document.getElementById(\"release\");\n"
  "\n"
  "  try {\n"
  "    const r=await fetch(\"qsoz?op=release\",{cache:\"no-store\"});\n"
  "    if(!r.ok)throw new Error(\"release\");\n"
  "    el.textContent=(await r.text()).trim();\n"
  "  }\n"
  "  catch {\n"
  "    el.textContent=\"?\";\n"
  "  }\n"
  "}\n"
  "\n"
  "releaseupdate();\n"
  "\n"
  "const SVG_NS=\"http://www.w3.org/2000/svg\";\n"
  "\n"
  "function svgNode(name,attrs={},text=\"\") {\n"
  "  const el=document.createElementNS(SVG_NS,name);\n"
  "  Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));\n"
  "  if(text)el.textContent=text;\n"
  "  return el;\n"
  "}\n"
  "\n"
  "function chartTime(epochSec) {\n"
  "  const d=new Date(epochSec*1000);\n"
  "  const dd=String(d.getDate()).padStart(2,\"0\");\n"
  "  const hh=String(d.getHours()).padStart(2,\"0\");\n"
  "  const mm=String(d.getMinutes()).padStart(2,\"0\");\n"
  "  return `${dd}-${hh}:${mm}`;\n"
  "}\n"
  "\n"
  "function drawChart(el,rows) {\n"
  "  const width=Math.max(500,el.clientWidth||500);\n"
  "  const height=Math.max(300,el.clientHeight||520);\n"
  "  const left=58,right=72,top=22,bottom=52;\n"
  "  const pw=width-left-right,ph=height-top-bottom;\n"
  "  const svg=svgNode(\"svg\",{viewBox:`0 0 ${width} ${height}`,width:\"100%\",height:\"100%\",\"aria-label\":\"Contest activity chart\",role:\"img\"});\n"
  "  let maxLeft=1,maxScore=1;\n"
  "\n"
  "  rows.forEach(r=>{\n"
  "    maxLeft=Math.max(maxLeft,Number(r[1])||0,Number(r[2])||0,Number(r[3])||0);\n"
  "    maxScore=Math.max(maxScore,Number(r[4])||0);\n"
  "  });\n"
  "  const x=i=>left+(rows.length<=1?pw/2:(i*pw/(rows.length-1)));\n"
  "  const yLeft=v=>top+ph-(Number(v)||0)*ph/maxLeft;\n"
  "  const yScore=v=>top+ph-(Number(v)||0)*ph/maxScore;\n"
  "\n"
  "  for(let i=0;i<=5;i++){\n"
  "    const y=top+ph*i/5;\n"
  "    const lv=Math.round(maxLeft*(5-i)/5);\n"
  "    const rv=Math.round(maxScore*(5-i)/5);\n"
  "    svg.appendChild(svgNode(\"line\",{x1:left,y1:y,x2:left+pw,y2:y,class:\"chart-grid\"}));\n"
  "    svg.appendChild(svgNode(\"text\",{x:left-8,y:y+4,\"text-anchor\":\"end\",class:\"chart-label\"},String(lv)));\n"
  "    svg.appendChild(svgNode(\"text\",{x:left+pw+8,y:y+4,\"text-anchor\":\"start\",class:\"chart-label\"},String(rv)));\n"
  "  }\n"
  "  svg.appendChild(svgNode(\"line\",{x1:left,y1:top,x2:left,y2:top+ph,class:\"chart-axis\"}));\n"
  "  svg.appendChild(svgNode(\"line\",{x1:left+pw,y1:top,x2:left+pw,y2:top+ph,class:\"chart-axis\"}));\n"
  "  svg.appendChild(svgNode(\"line\",{x1:left,y1:top+ph,x2:left+pw,y2:top+ph,class:\"chart-axis\"}));\n"
  "\n"
  "  const ticks=Math.min(8,rows.length);\n"
  "  for(let i=0;i<ticks;i++){\n"
  "    const idx=ticks<=1?0:Math.round(i*(rows.length-1)/(ticks-1));\n"
  "    const xx=x(idx);\n"
  "    svg.appendChild(svgNode(\"line\",{x1:xx,y1:top+ph,x2:xx,y2:top+ph+5,class:\"chart-axis\"}));\n"
  "    svg.appendChild(svgNode(\"text\",{x:xx,y:top+ph+20,\"text-anchor\":\"middle\",class:\"chart-label\"},chartTime(rows[idx][0])));\n"
  "  }\n"
  "\n"
  "  const defs=[\n"
  "    [1,yLeft,\"QSO\",\"chart-series chart-qso\"],\n"
  "    [2,yLeft,\"Points\",\"chart-series chart-points\"],\n"
  "    [3,yLeft,\"Mults\",\"chart-series chart-mults\"],\n"
  "    [4,yScore,\"Score\",\"chart-series chart-score\"]\n"
  "  ];\n"
  "  defs.forEach(def=>{\n"
  "    const points=rows.map((r,i)=>`${x(i)},${def[1](r[def[0]])}`).join(\" \");\n"
  "    if(points)svg.appendChild(svgNode(\"polyline\",{points,class:def[3]}));\n"
  "  });\n"
  "\n"
  "  let lx=left;\n"
  "  defs.forEach(def=>{\n"
  "    svg.appendChild(svgNode(\"line\",{x1:lx,y1:height-14,x2:lx+22,y2:height-14,class:def[3]}));\n"
  "    svg.appendChild(svgNode(\"text\",{x:lx+28,y:height-10,class:\"chart-label\"},def[2]));\n"
  "    lx+=92;\n"
  "  });\n"
  "  svg.appendChild(svgNode(\"text\",{x:14,y:top+ph/2,transform:`rotate(-90 14 ${top+ph/2})`,\"text-anchor\":\"middle\",class:\"chart-label\"},\"QSO / Points / Mults\"));\n"
  "  svg.appendChild(svgNode(\"text\",{x:width-12,y:top+ph/2,transform:`rotate(90 ${width-12} ${top+ph/2})`,\"text-anchor\":\"middle\",class:\"chart-label\"},\"Score\"));\n"
  "  el.replaceChildren(svg);\n"
  "}\n"
  "\n"
  "function renderCharts(root=document) {\n"
  "  root.querySelectorAll(\".gchart\").forEach(el=>{\n"
  "    let rows;\n"
  "    try { rows=JSON.parse(el.dataset.rows); }\n"
  "    catch { el.textContent=\"Invalid chart data\"; return; }\n"
  "    if(!Array.isArray(rows) || rows.length===0){el.textContent=\"No chart data\"; return;}\n"
  "    const draw=()=>drawChart(el,rows);\n"
  "    draw();\n"
  "    if(!el._qsozResizeObserver){\n"
  "      el._qsozResizeObserver=new ResizeObserver(draw);\n"
  "      el._qsozResizeObserver.observe(el);\n"
  "    }\n"
  "  });\n"
  "}\n"
  "\n"
  "window.openImgExact = (url) => {\n"
  "  const win = window.open(\"\", \"img\", \"width=200,height=200,resizable=1,scrollbars=0\");\n"
  "  if (!win) return false;\n"
  "  win.document.title = \"Image\";\n"
  "  const style = win.document.createElement(\"style\");\n"
  "  style.textContent = \"html,body{margin:0;padding:0;overflow:hidden} img{display:block}\";\n"
  "  const im = win.document.createElement(\"img\");\n"
  "  im.id = \"i\";\n"
  "  im.src = url;\n"
  "  win.document.head.replaceChildren(style);\n"
  "  win.document.body.replaceChildren(im);\n"
  "  im.onload = () => {\n"
  "    const w = im.naturalWidth;\n"
  "    const h = im.naturalHeight;\n"
  "    const fit = () => win.resizeTo(\n"
  "      win.outerWidth + (w - win.innerWidth),\n"
  "      win.outerHeight + (h - win.innerHeight)\n"
  "    );\n"
  "    fit();\n"
  "    requestAnimationFrame(fit);\n"
  "    setTimeout(fit, 50);\n"
  "  };\n"
  "  return false;\n"
  "};\n"
  "  \n"
  "</script>\n"
  "</body>\n"
  "\n";

int qsoz_frontend_main(void) {
  printf("Content-Type: text/html; charset=utf-8\r\n\r\n");
  fwrite(qsoz_page,1,sizeof(qsoz_page)-1,stdout);
  return 0;
}
